/** Typed error codes (§43). Consistent error envelope for HTTP and WS. */
export const ErrorCode = {
  // Validation / generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Auth
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  SESSION_REVOKED: 'SESSION_REVOKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERNAME_INVALID: 'USERNAME_INVALID',

  // Games
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',
  GAME_NOT_ACTIVE: 'GAME_NOT_ACTIVE',
  GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
  GAME_ALREADY_FINISHED: 'GAME_ALREADY_FINISHED',
  NOT_GAME_PLAYER: 'NOT_GAME_PLAYER',
  NOT_YOUR_TURN: 'NOT_YOUR_TURN',
  ILLEGAL_MOVE: 'ILLEGAL_MOVE',
  MOVE_SYNC_REQUIRED: 'MOVE_SYNC_REQUIRED',
  PROMOTION_PIECE_REQUIRED: 'PROMOTION_PIECE_REQUIRED',
  GAME_CODE_INVALID: 'GAME_CODE_INVALID',
  GAME_FULL: 'GAME_FULL',
  TOO_MANY_ACTIVE_GAMES: 'TOO_MANY_ACTIVE_GAMES',

  // Matchmaking
  ALREADY_IN_QUEUE: 'ALREADY_IN_QUEUE',
  NOT_IN_QUEUE: 'NOT_IN_QUEUE',

  // Draw / resign / rematch
  DRAW_OFFER_NOT_FOUND: 'DRAW_OFFER_NOT_FOUND',
  DRAW_OFFER_ALREADY_PENDING: 'DRAW_OFFER_ALREADY_PENDING',
  CANNOT_RESIGN_FINISHED_GAME: 'CANNOT_RESIGN_FINISHED_GAME',
  REMATCH_NOT_ALLOWED: 'REMATCH_NOT_ALLOWED',

  // Friends
  FRIEND_REQUEST_EXISTS: 'FRIEND_REQUEST_EXISTS',
  ALREADY_FRIENDS: 'ALREADY_FRIENDS',
  NOT_FRIENDS: 'NOT_FRIENDS',
  CANNOT_ADD_SELF: 'CANNOT_ADD_SELF',
  BLOCKED_BY_USER: 'BLOCKED_BY_USER',
  USER_BLOCKED_TARGET: 'USER_BLOCKED_TARGET',

  // Chat
  CHAT_DISABLED: 'CHAT_DISABLED',
  CHAT_RATE_LIMITED: 'CHAT_RATE_LIMITED',

  // Sockets
  SOCKET_UNAUTHORIZED: 'SOCKET_UNAUTHORIZED',
  NOT_IN_GAME_ROOM: 'NOT_IN_GAME_ROOM',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  details?: unknown;
}

export interface ApiSuccess<T> {
  success: true;
  data: T;
}

export interface ApiFailure {
  success: false;
  error: ApiErrorBody;
}

export type ApiResponse<T> = ApiSuccess<T> | ApiFailure;

/** Maps HTTP status for well-known codes; unknown codes should default to 500. */
export const ERROR_HTTP_STATUS: Record<ErrorCode, 400 | 401 | 403 | 404 | 409 | 423 | 429 | 500 | 503> = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  EMAIL_TAKEN: 409,
  USERNAME_TAKEN: 409,
  INVALID_CREDENTIALS: 401,
  INVALID_REFRESH_TOKEN: 401,
  SESSION_REVOKED: 401,
  ACCOUNT_SUSPENDED: 403,
  ACCOUNT_BANNED: 403,
  ACCOUNT_LOCKED: 423,
  EMAIL_NOT_VERIFIED: 403,
  USER_NOT_FOUND: 404,
  USERNAME_INVALID: 400,
  GAME_NOT_FOUND: 404,
  GAME_NOT_ACTIVE: 409,
  GAME_ALREADY_STARTED: 409,
  GAME_ALREADY_FINISHED: 409,
  NOT_GAME_PLAYER: 403,
  NOT_YOUR_TURN: 409,
  ILLEGAL_MOVE: 400,
  MOVE_SYNC_REQUIRED: 409,
  PROMOTION_PIECE_REQUIRED: 400,
  GAME_CODE_INVALID: 404,
  GAME_FULL: 409,
  TOO_MANY_ACTIVE_GAMES: 409,
  ALREADY_IN_QUEUE: 409,
  NOT_IN_QUEUE: 409,
  DRAW_OFFER_NOT_FOUND: 404,
  DRAW_OFFER_ALREADY_PENDING: 409,
  CANNOT_RESIGN_FINISHED_GAME: 409,
  REMATCH_NOT_ALLOWED: 409,
  FRIEND_REQUEST_EXISTS: 409,
  ALREADY_FRIENDS: 409,
  NOT_FRIENDS: 404,
  CANNOT_ADD_SELF: 400,
  BLOCKED_BY_USER: 403,
  USER_BLOCKED_TARGET: 403,
  CHAT_DISABLED: 403,
  CHAT_RATE_LIMITED: 429,
  SOCKET_UNAUTHORIZED: 401,
  NOT_IN_GAME_ROOM: 403,
};
